name: Run Test

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Build Image
        run: docker build -t signalwire-python-sdk .
      - name: Run Tests
        run: docker run signalwire-python-sdk